create table public."Ventas" (
  id bigint generated always as identity primary key,
  tipo_documento text,
  fecha_contabilizacion date,
  num_documento bigint,
  vendedor_senior text,
  vendedor_junior text,
  tipo_venta text,
  zona text,
  territorio text,
  grupo_cliente text,
  subgrupo_cliente text,
  cod_cliente text,
  nombre_cliente text,
  codigo_punto_venta text,
  descripcion_punto_venta text,
  centro_costos text,
  grupo_articulo text,
  familia text,
  codigo_articulo text,
  descripcion_articulo text,
  planta text,
  componente_kit text,
  cantidad numeric,
  precio_venta numeric,
  descuento_pct numeric,
  precio_tras_descuento numeric,
  valor_total numeric,
  costo numeric,
  costo_total numeric,
  contribucion_bruta numeric,
  margen_bruta numeric,
  obra text,
  ciudad text,
  telefono text,
  fecha_fin_novedad date,
  segmento_cliente text,
  estrategia_cliente text,
  tipo_cliente text,
  codigo_tipo_nc text,
  tipos_nc text,
  codigo_concepto_nc text,
  conceptos_notas_credito text,
  comentarios text,
  created_at timestamptz default now()
);
